version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "LGUG2Z"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "LGUG2Z"
    commit-message:
      prefix: chore
      include: scope
