# Adapted from https://jondot.medium.com/shipping-rust-binaries-with-goreleaser-d5aa42a46be0
project_name: komorebi

before:
  hooks:
    - powershell.exe -Command "New-Item -Path . -Name dummy.go -ItemType file -Force"
    - powershell.exe -Command "Add-Content -Path .\dummy.go -Value 'package main'"
    - powershell.exe -Command "Add-Content -Path .\dummy.go -Value 'func main() {}'"

builds:
  - id: komorebi
    main: dummy.go
    goos: ["windows"]
    goarch: ["amd64"]
    binary: komorebi
    hooks:
      post:
        - mkdir -p dist/windows_amd64
        - cp ".\target\x86_64-pc-windows-msvc\release\komorebi.exe" ".\dist\komorebi_windows_amd64_v1\komorebi.exe"
  - id: komorebic
    main: dummy.go
    goos: ["windows"]
    goarch: ["amd64"]
    binary: komorebic
    hooks:
      post:
        - mkdir -p dist/windows_amd64
        - cp ".\target\x86_64-pc-windows-msvc\release\komorebic.exe" ".\dist\komorebic_windows_amd64_v1\komorebic.exe"
  - id: komorebic-no-console
    main: dummy.go
    goos: ["windows"]
    goarch: ["amd64"]
    binary: komorebic-no-console
    hooks:
      post:
        - mkdir -p dist/windows_amd64
        - cp ".\target\x86_64-pc-windows-msvc\release\komorebic-no-console.exe" ".\dist\komorebic-no-console_windows_amd64_v1\komorebic-no-console.exe"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-x86_64-pc-windows-msvc"
    format: zip
    files:
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
