name: Bug report
description: File a bug report
labels: [bug]
title: "[BUG]: "
body:
  - type: markdown
    attributes:
      value: |
        Please **do not** open an issue for applications with invisible windows leaving ghost tiles.

        You can run `komorebic visible-windows` when the ghost tile is present on your workspace to retrieve the invisible window's exe, class name and title, and then use that information to [ignore the window](https://lgug2z.github.io/komorebi/common-workflows/ignore-windows.html) responsible for the ghost tile.

        If it is not possible to uniquely identify the invisible window resulting in a ghost tile through a mixture of exe, title and class identifiers, then this is not a bug with komorebi but a bug with the application you are using, and you should open an issue with the developer(s) of that application.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel is relevant to replicating the bug.

        You may include screenshots and videos in this section.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Version Information
      description: >
        Please provide information about the versions of Windows and komorebi
        running on your machine.

        Do not submit a bug if you are not using an official version of Windows
        such as AtlasOS; only official versions of Windows are supported.

        ```
        systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
        ```

        ```
        komorebic --version
        ```
  - type: textarea
    validations:
      required: true
    attributes:
      label: Komorebi Configuration
      description: >
        Please provide your configuration file (komorebi.json or komorebi.bar.json)
      render: json
  - type: textarea
    validations:
      required: true
    attributes:
      label: Hotkey Configuration
      description: >
        Please provide your whkdrc or komorebi.ahk hotkey configuration file
  - type: textarea
    validations:
      required: true
    attributes:
      label: Output of komorebic check
      description: >
        Please provide the output of `komorebic check`
