name: Feature request
description: Suggest a new feature (Limited to Sponsors, Commercial License Holders, and Collaborators)
labels: [enhancement]
title: "[FEAT]: "
body:
  - type: dropdown
    id: Eligibility
    attributes:
      label: Eligibility
      description: >
        Feature requests are considered from individuals who are current $5+ monthly sponsors to the project, individual commercial use license holders, and approved collaborators.

        Please specify the platform you use to sponsor the project.
      options:
        - Individual Commercial Use License
        - GitHub Sponsor
        - Ko-fi Sponsor
        - Approved Collaborator
      default: 0
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Suggestion
      description: >
        Please share your suggestion here. Be sure to include all necessary context.

        If you sponsor on a platform where you use a different username, please specify the username here.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Alternatives Considered
      description: >
        Please share share alternatives you have considered here.
